In [2]:
import numpy as np 
import cv2 as cv

In [38]:
img = cv.imread('pic2.png', 0)
print(img)


[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


[[1]
 [0]
 [0]
 [0]]


True

In [51]:
arr = img[1:3,0:3]

print(arr);

[[198 125 255]
 [209 134 255]]
